### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [bobrocke/topicmenu#1]
The plugin TopicMenu can't be configured using the new [Grav's Admin Panel](https://github.com/getgrav/grav-plugin-admin). For example, if we go to the settings page of the plugin (url `/admin/plugins/topicmenu`) and click on *Save*, there's the following error:

> **Validation failed:** page_path is not defined in blueprints

According to a Grav developer: "These plugins just need to get updated with appropriate blueprint files so they will work in the admin plugin."

My config: Grav v0.9.39, Admin Panel v0.4.2, TopicMenu v1.0.0

**Comment by bobrocke** [comment]
Fixed in v1.1.0.
