### ISSUE TITLE
Call to a member function children() on a non-object

### ISSUE THREAD

**Issue by neosin** [bobrocke/topicmenu#2]
hello, when i install this plugin and activate it my site shows this error

`[2015-11-11 17:18:44] grav.CRITICAL: Call to a member function children() on a non-object - Trace: #0 C:\xampp\htdocs\__mynews\grav\vendor\filp\whoops\src\Whoops\Run.php(357): Whoops\Run->handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 62) #1 [internal function]: Whoops\Run->handleShutdown() #2 {main} [] []`

**Comment by bobrocke** [comment]
@neosin Does this happen when installing from the CLI, or the Admin? Do you see the error immediately on installation, or at the the first page refresh/load? Did you clear the cache after installing?
