### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by MichelleDiamond** [bobrocke/topicmenu#4]
Grav v1.1.17 - Admin v1.2.14

0 - Call to a member function children() on null

**Comment by bobrocke** [comment]
I will have to see what's happening. Thanks for the heads up.

Bob  
——
Bob Rockefeller
Midway, GA
www.bobrockefeller.com

**Comment by bobrocke** [comment]
Where are you seeing this error? I haven't hit it, yet.
